control_mode_switcher:
    control_mode_to_controllers:
        # global settings
        all:
            transitions:
                - "stop"

        # "none" should be the first controller defined (No controllers active)
        none:
            transitions:
                - "stand_prep"

        # Force a reset of all controllers and footsteps (trajectory controllers reset to hold current position)
        stop:
            ctrl_modules: ["base_module"]
            transitions:
                - "whole_body"
                - "stand"
                - "shutdown"

        stand_prep:
            ctrl_modules: ["base_module"]
            transitions:
                - "stand"

        stand:
            ctrl_modules: ["base_module"]
            joint_ctrl_modules: 
               - ros_control_module: ["head_p", "head_y", "torso_y", "l_arm_sh_p1", "l_arm_sh_r", "l_arm_sh_p2", "l_arm_el_y", "l_arm_wr_r", "l_arm_wr_y", "l_arm_wr_p", "r_arm_sh_p1", "r_arm_sh_r", "r_arm_sh_p2", "r_arm_el_y", "r_arm_wr_r", "r_arm_wr_y", "r_arm_wr_p"]
            desired_controllers_to_start: ["head_traj_controller", "torso_traj_controller", "left_arm_traj_controller", "right_arm_traj_controller"]
            transitions:
                - "walk"
                - "walk_manipulate"
                - "manipulate"

        walk:
            ctrl_modules: ["base_module", "walk_control_module"]
            transitions:
                - "walk_manipulate"
                - "stand"
                - "stop"

        walk_manipulate:
            joint_ctrl_modules: 
               - ros_control_module: ["head_p", "head_y", "torso_y", "l_arm_sh_p1", "l_arm_sh_r", "l_arm_sh_p2", "l_arm_el_y", "l_arm_wr_r", "l_arm_wr_y", "l_arm_wr_p", "r_arm_sh_p1", "r_arm_sh_r", "r_arm_sh_p2", "r_arm_el_y", "r_arm_wr_r", "r_arm_wr_y", "r_arm_wr_p"]
               - walk_control_module: ["l_leg_hip_y", "l_leg_hip_r", "l_leg_hip_p", "l_leg_kn_p", "l_leg_an_p", "l_leg_an_r", "r_leg_hip_y", "r_leg_hip_r", "r_leg_hip_p", "r_leg_kn_p", "r_leg_an_p", "r_leg_an_r"]
            desired_controllers_to_start: ["head_traj_controller", "torso_traj_controller", "left_arm_traj_controller", "right_arm_traj_controller"]
            transitions:
                - "walk"
                - "stand"

        manipulate:
            ctrl_modules: ["base_module"]
            joint_ctrl_modules: 
               - ros_control_module: ["head_p", "head_y", "torso_y", "l_arm_sh_p1", "l_arm_sh_r", "l_arm_sh_p2", "l_arm_el_y", "l_arm_wr_r", "l_arm_wr_y", "l_arm_wr_p", "r_arm_sh_p1", "r_arm_sh_r", "r_arm_sh_p2", "r_arm_el_y", "r_arm_wr_r", "r_arm_wr_y", "r_arm_wr_p"]
            desired_controllers_to_start: ["head_traj_controller", "torso_traj_controller", "left_arm_traj_controller", "right_arm_traj_controller"]
            transitions:
                - "walk_manipulate"
                - "stand"
                - "manipulate_compliant_admittance"

        whole_body:
            ctrl_ctrl_modules: ["ros_control_module"]            
            desired_controllers_to_start: ["head_traj_controller", "torso_traj_controller", "left_arm_traj_controller", "right_arm_traj_controller", " left_leg_traj_controller", "right_leg_traj_controller"]
            transitions:
                - "freeze"
                - "manipulate"

        manipulate_compliant_admittance:
            ctrl_ctrl_modules: ["base_module", "ros_control_module"]            
            desired_controllers_to_start: ["head_traj_controller", "torso_traj_controller", "left_arm_traj_controller", "right_arm_traj_controller"]
            transitions:
                - "stand"
                - "manipulate"

        shutdown:
            ctrl_ctrl_modules: ["ros_control_module"]
            desired_controllers_to_start: ["head_traj_controller", "torso_traj_controller", "left_arm_traj_controller", "right_arm_traj_controller", " left_leg_traj_controller", "right_leg_traj_controller"]
            transitions:
                - "stop"
