control_mode_switcher:
    control_mode_to_controllers:
        # global settings
        all:
            desired_controllers_to_start: ["head_traj_controller", "left_hand_traj_controller", "right_hand_traj_controller"]
            transitions:
                - "stop"

        # "none" should be the first controller defined (No controllers active)
        none:
            transitions:
                - "stand_prep"

        # Force a reset of all controllers and footsteps (trajectory controllers reset to hold current position)
        stop:
            ctrl_modules: ["base_module"]
            transitions:
                - "whole_body"
                - "stand"
                - "shutdown"

        stand_prep:
            ctrl_modules: ["base_module"]
            transitions:
                - "stand"

        stand:
            ctrl_modules: ["base_module"]
            desired_controllers_to_start: ["torso_traj_controller", "left_arm_traj_controller", "right_arm_traj_controller"]
            transitions:
                - "walk"
                - "l3_walk"
                - "manipulate"
                - "walk_manipulate"
                - "whole_body"

        walk:
            ctrl_modules: ["base_module", "walking_module"]
            transitions:
                - "walk_manipulate"
                - "stand"
                - "stop"

        l3_walk:
            ctrl_modules: ["base_module", "l3_module"]
            transitions:
                - "walk_manipulate"
                - "stand"
                - "stop"

        walk_manipulate:
            joint_ctrl_modules: 
               - walking_module: ["l_leg_hip_y", "l_leg_hip_r", "l_leg_hip_p", "l_leg_kn_p", "l_leg_an_p", "l_leg_an_r", "r_leg_hip_y", "r_leg_hip_r", "r_leg_hip_p", "r_leg_kn_p", "r_leg_an_p", "r_leg_an_r"]
            desired_controllers_to_start: ["torso_traj_controller", "left_arm_traj_controller", "right_arm_traj_controller"]
            transitions:
                - "walk"
                - "stand"

        manipulate:
            ctrl_modules: ["base_module"]
            desired_controllers_to_start: ["torso_traj_controller", "left_arm_traj_controller", "right_arm_traj_controller"]
            transitions:
                - "stand"
                - "walk_manipulate"
                - "whole_body"
                - "manipulate_compliant_admittance"

        whole_body:           
            desired_controllers_to_start: ["torso_traj_controller", "left_arm_traj_controller", "right_arm_traj_controller", "left_leg_traj_controller", "right_leg_traj_controller"]
            transitions:
                - "stand"
                - "stop"
                - "manipulate"
                - "walk_manipulate"

        manipulate_compliant_admittance:
            ctrl_modules: ["base_module"]            
            desired_controllers_to_start: ["torso_traj_controller", "right_arm_compliant_controller", "left_arm_compliant_controller"]
            transitions:
                - "stand"
                - "manipulate"

        shutdown:
            desired_controllers_to_start: ["torso_traj_controller", "left_arm_traj_controller", "right_arm_traj_controller", "left_leg_traj_controller", "right_leg_traj_controller"]
            transitions:
                - "stop"
